const stateKey="career-dashboard-state-v1";
let data;
let state=JSON.parse(localStorage.getItem(stateKey)||'{"tasks":{}}');

const glossary={
 capm:{title:"CAPM",simple:"Certified Associate in Project Management, a foundational PMI certification that validates project-management knowledge.",example:"Your CAPM study supports Project Coordinator and PM-track roles.",visual:["PM KNOWLEDGE","↓","CAPM","↓","PM-TRACK ROLES"]},
 workstream:{title:"Workstream",simple:"A major category of related work inside a larger project.",example:"Your career project has PM/CAPM, Technical Skills, Portfolio and Job Search workstreams.",visual:["PROJECT","↓","WORKSTREAMS","↓","DELIVERABLES → TASKS"]},
 deliverable:{title:"Deliverable",simple:"A specific result, product, document or outcome the project must produce.",example:"A configured POS workflow or completed project charter can be a deliverable.",visual:["WORKSTREAM","↓","DELIVERABLE","↓","TASKS"]},
 dependency:{title:"Dependency",simple:"Something that must happen before another piece of work can move forward.",example:"TikTok Go manager training depends on the redemption process being defined first.",visual:["A MUST FINISH","→","B CAN START"]},
 milestone:{title:"Milestone",simple:"An important project checkpoint or event, usually with no duration.",example:"TikTok Go go-live is a milestone.",visual:["WORK","→","◆ MILESTONE","→","NEXT PHASE"]},
 stakeholder:{title:"Stakeholder",simple:"A person or group that can affect the project, is affected by it, or cares about its outcome.",example:"IT, Marketing, TikTok, managers and restaurant teams are TikTok Go stakeholders.",visual:["IT · MARKETING · TIKTOK","↘  ↓  ↙","PROJECT","↓","MANAGERS · STAFF"]},
 risk:{title:"Risk",simple:"An uncertain event that might happen and affect the project. If it has already happened, it is an issue.",example:"A location tablet might be unable to install the TikTok merchant app.",visual:["MIGHT HAPPEN = RISK","↓ happens","IS HAPPENING = ISSUE"]},
 scope:{title:"Scope",simple:"The boundaries of the project: what work is included and what is not.",example:"TikTok Go scope includes device readiness, POS/menu configuration, training and launch coordination.",visual:["PROJECT BOUNDARY","[ INCLUDED WORK ]","OUTSIDE = NOT IN SCOPE"]},
 raci:{title:"RACI",simple:"A responsibility chart showing who is Responsible, Accountable, Consulted and Informed.",example:"Use it to distinguish work you coordinate from work Marketing, Operations or another owner performs.",visual:["R = DOES IT","A = OWNS IT","C = GIVES INPUT","I = KEPT UPDATED"]},
 jira:{title:"Jira",simple:"A work-management platform used to organize, assign and track project work.",example:"We are using TikTok Go as your first live Jira planning project.",visual:["PROJECT","↓","WORK ITEMS","↓","OWNER · STATUS · DUE DATE"]},
 epic:{title:"Epic",simple:"A large body of work that can be broken into smaller work items. Jira configurations vary, but Epics are commonly used to group related project work.",example:"Location & Device Readiness could be an Epic containing separate location-readiness tasks.",visual:["EPIC","↓","TASKS","↓","SUBTASKS"]}
};

function save(){localStorage.setItem(stateKey,JSON.stringify(state));}
function ensureTask(id){if(!state.tasks[id])state.tasks[id]={done:false,checks:{},steps:{},notes:""};if(!state.tasks[id].steps)state.tasks[id].steps={};return state.tasks[id];}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function termButton(term,label){return `<button type="button" class="term" data-term="${term}">${label||glossary[term].title}</button>`;}
function linkifyTerms(text){let s=escapeHtml(text);[[/\bCAPM\b/g,"capm"],[/\bworkstreams?\b/gi,"workstream"],[/\bdeliverables?\b/gi,"deliverable"],[/\bdependencies\b|\bdependency\b/gi,"dependency"],[/\bmilestones?\b/gi,"milestone"],[/\bstakeholders?\b/gi,"stakeholder"],[/\brisks?\b/gi,"risk"],[/\bscope\b/gi,"scope"],[/\bRACI\b/g,"raci"],[/\bJira\b/g,"jira"],[/\bEpics?\b/g,"epic"]].forEach(([re,key])=>{s=s.replace(re,m=>termButton(key,m));});return s;}
function formatDate(t){if(!t.date)return t.day;return new Date(`${t.date}T12:00:00`).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"});}

function openTerm(key){const g=glossary[key];if(!g)return;let m=document.getElementById("termModal");if(!m){m=document.createElement("div");m.id="termModal";m.className="term-modal hidden";m.innerHTML='<div class="term-backdrop"></div><section class="term-dialog"><button class="term-close" type="button">×</button><div class="kicker">Interactive learning card</div><h2></h2><p class="term-simple"></p><div class="term-example"></div><div class="term-visual"></div></section>';document.body.appendChild(m);m.querySelector(".term-close").onclick=()=>m.classList.add("hidden");m.querySelector(".term-backdrop").onclick=()=>m.classList.add("hidden");}m.querySelector("h2").textContent=g.title;m.querySelector(".term-simple").textContent=g.simple;m.querySelector(".term-example").innerHTML=`<strong>Real example:</strong> ${g.example}`;m.querySelector(".term-visual").innerHTML=g.visual.map(x=>`<div>${x}</div>`).join("");m.classList.remove("hidden");}
document.addEventListener("click",e=>{const b=e.target.closest(".term");if(b){e.preventDefault();openTerm(b.dataset.term);}});
document.addEventListener("keydown",e=>{if(e.key==="Escape")document.getElementById("termModal")?.classList.add("hidden");});

function renderStats(){const cats=["PM / CAPM","Technical","Portfolio","Job Search"],box=document.getElementById("stats");box.innerHTML="";cats.forEach(cat=>{const ts=data.tasks.filter(t=>t.category===cat),done=ts.filter(t=>ensureTask(t.id).done).length,pct=ts.length?Math.round(done/ts.length*100):0;box.insertAdjacentHTML("beforeend",`<div class="stat"><div class="stat-label">${linkifyTerms(cat)}</div><div class="bar"><div class="fill" style="width:${pct}%"></div></div><div class="stat-pct">${pct}%</div></div>`);});}

function normalizeItem(item){return typeof item==="string"?{title:item,description:"",steps:[]}:item;}
function makeTask(task){const tpl=document.getElementById("taskTemplate"),el=tpl.content.firstElementChild.cloneNode(true),s=ensureTask(task.id);el.dataset.id=task.id;el.classList.toggle("done",s.done);el.querySelector(".task-title").innerHTML=linkifyTerms(task.title);el.querySelector(".minutes").textContent=`${task.minutes} min`;el.querySelector(".meta").innerHTML=`${formatDate(task)} · ${linkifyTerms(task.category)}`;el.querySelector(".details").innerHTML=linkifyTerms(task.details);const main=el.querySelector(".task-check");main.checked=s.done;main.onchange=()=>{s.done=main.checked;save();renderAll();};const list=el.querySelector(".checklist");
 task.checklist.forEach((raw,i)=>{const item=normalizeItem(raw),wrap=document.createElement("div");wrap.className="check-group";const head=document.createElement("div");head.className="check-group-head";const cb=document.createElement("input");cb.type="checkbox";cb.className="subcheck";cb.checked=!!s.checks[i];cb.onchange=()=>{s.checks[i]=cb.checked;save();};const content=document.createElement("div");content.className="check-content";content.innerHTML=`<div class="check-title">${linkifyTerms(item.title)}</div>${item.description?`<div class="check-description">${linkifyTerms(item.description)}</div>`:""}`;head.append(cb,content);wrap.appendChild(head);
  if(item.steps?.length){const details=document.createElement("details");details.className="step-panel";details.innerHTML=`<summary>Show exactly what to do <span class="step-count">${item.steps.length} steps</span></summary>`;const steps=document.createElement("div");steps.className="steps";item.steps.forEach((step,j)=>{const row=document.createElement("label");row.className="step-row";const sc=document.createElement("input");sc.type="checkbox";const key=`${i}:${j}`;sc.checked=!!s.steps[key];sc.onchange=()=>{s.steps[key]=sc.checked;save();};const tx=document.createElement("span");tx.innerHTML=linkifyTerms(step);row.append(sc,tx);steps.appendChild(row);});details.appendChild(steps);wrap.appendChild(details);}
  list.appendChild(wrap);
 });
 const notes=el.querySelector(".notes");notes.value=s.notes||"";notes.oninput=()=>{s.notes=notes.value;save();};return el;}

function renderDaily(){const box=document.getElementById("daily"),today=new Date().toLocaleDateString("en-CA"),sorted=[...data.tasks].sort((a,b)=>a.date.localeCompare(b.date));let task=sorted.find(t=>t.date===today&&!ensureTask(t.id).done)||sorted.find(t=>t.date===today)||sorted.find(t=>!ensureTask(t.id).done&&t.date<today)||sorted.find(t=>!ensureTask(t.id).done);box.innerHTML="";if(!task){box.innerHTML='<div class="empty">Everything currently listed is complete.</div>';return;}box.innerHTML=`<div class="today-hero"><div class="kicker">Current daily task</div><h2>${escapeHtml(task.title)}</h2><p>${formatDate(task)} · ${task.minutes} minutes</p><p class="sub">Open each checklist section below. The heading tells you the outcome, the description tells you why it matters, and <strong>Show exactly what to do</strong> gives you the concrete steps.</p></div>`;box.appendChild(makeTask(task));}
function renderWeekly(){const box=document.getElementById("weekly");box.innerHTML="";const groups={};[...data.tasks].sort((a,b)=>a.date.localeCompare(b.date)).forEach(t=>{const k=`${t.month} · ${t.week}`;(groups[k]??=[]).push(t);});Object.entries(groups).forEach(([k,ts])=>{const sec=document.createElement("section");sec.className="day-block";sec.innerHTML=`<div class="day-label">${escapeHtml(k)}</div><div class="grid"></div>`;ts.forEach(t=>sec.querySelector(".grid").appendChild(makeTask(t)));box.appendChild(sec);});}
function renderMonthly(){const box=document.getElementById("monthly");box.innerHTML='<div class="grid two"></div>';const grid=box.firstElementChild;data.months.forEach(m=>{const c=document.createElement("article");c.className="card month-card";c.innerHTML=`<div class="kicker">${escapeHtml(m.month)}</div><h3>${linkifyTerms(m.focus)}</h3><ul>${m.items.map(x=>`<li>${linkifyTerms(x)}</li>`).join("")}</ul>`;grid.appendChild(c);});}
function renderAll(){renderStats();renderDaily();renderWeekly();renderMonthly();}

document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));document.getElementById(b.dataset.view).classList.remove("hidden");});
document.getElementById("resetBtn").onclick=()=>{if(confirm("Reset all saved progress and notes on this browser?")){state={tasks:{}};save();renderAll();}};
fetch("roadmap.json").then(r=>r.json()).then(d=>{data=d;renderAll();}).catch(()=>{document.getElementById("daily").innerHTML='<div class="empty">Could not load roadmap.json.</div>';});