const stateKey="career-dashboard-state-v1";
let data;
let state=JSON.parse(localStorage.getItem(stateKey)||'{"tasks":{}}');

const glossary={
 capm:{title:"CAPM",simple:"A beginner-level project management certification.",analogy:"Think of it like proof that you understand the basic language and rules of project management, even if your job title has never been Project Manager.",example:"For your career plan, CAPM helps show employers that you understand how projects are planned, organized, tracked and completed.",industry:"Certified Associate in Project Management, a PMI certification focused on foundational project-management knowledge.",visual:["LEARN PM BASICS","↓","CAPM","↓","SHOW PM KNOWLEDGE","↓","PM-TRACK ROLES"],capm:"CAPM is the certification itself, so this concept is directly tied to your exam preparation."},
 workstream:{title:"Workstream",simple:"One big section of a project.",analogy:"Think of a restaurant. The kitchen, dining room and bar are different sections, but they all work together to run the restaurant. A project can be split into big sections the same way.",example:"For a restaurant opening, IT, Marketing, Operations, Supply Chain and Construction can each be workstreams. For TikTok Go, IT setup, Marketing launch coordination and Operations/Training can be separate workstreams.",confused:"Workstream = the work. Stakeholder = the person or group involved in or affected by the work. Example: the IT workstream is the technology work; the IT team is a stakeholder group doing that work.",industry:"A workstream is a major group of related activities within a larger project or program. Workstreams can be organized by department, phase, system, location or another logical body of work.",visual:["RESTAURANT OPENING","↓","IT | MARKETING | OPERATIONS | SUPPLY CHAIN","↓","EACH = A WORKSTREAM","↓","ALL SUPPORT THE SAME PROJECT"],capm:"You may see the idea of breaking large project work into organized groups, even if the exact word workstream is not always the focus of a question."},
 deliverable:{title:"Deliverable",simple:"Something the project is supposed to produce or finish.",analogy:"If you order a cake, the finished cake is the thing you expect to receive. In a project, that finished result is a deliverable.",example:"For TikTok Go, a completed manager training guide or a working voucher redemption process can be deliverables. For Mikan, a configured POS setup or completed network installation can be deliverables.",confused:"Deliverable = finished result. Task = work you do to create that result. Example: 'Build training guide' is a task; the finished training guide is the deliverable.",industry:"A deliverable is a unique and verifiable product, result or capability produced to complete a process, phase or project.",visual:["TASKS","↓","CREATE SOMETHING","↓","DELIVERABLE"],capm:"CAPM-style questions often test whether you can distinguish project work from the output that work creates."},
 dependency:{title:"Dependency",simple:"Something that has to happen before something else can happen.",analogy:"You cannot bake a cake before you have the ingredients. The baking depends on the ingredients being available first.",example:"TikTok Go: a manager cannot be fully trained on redemption until the voucher process is defined. A location cannot be marked ready until the tablet can install the merchant app.",confused:"Dependency = one thing relies on another. Risk = something uncertain that might cause a problem. A dependency can be completely known and planned.",industry:"A dependency is a logical relationship in which one activity or event relies on another activity or event.",visual:["TABLET COMPATIBLE","→","APP INSTALLED","→","MANAGER TRAINED","→","LOCATION READY"],capm:"CAPM questions may ask you to recognize sequencing relationships between activities and what must happen first."},
 milestone:{title:"Milestone",simple:"An important checkpoint in the project.",analogy:"Think of a road trip. Reaching Las Vegas might be a major checkpoint, even though 'reaching Las Vegas' is not hours of work by itself.",example:"TikTok Go go-live is a milestone. Mikan grand opening is a milestone. Passing your CAPM exam can be a milestone in your career project.",confused:"Milestone = important point or event. Task = work that takes time. A milestone usually marks progress and typically has no duration.",industry:"A milestone is a significant point or event in a project, program or portfolio.",visual:["PROJECT WORK","→","◆ GO-LIVE","→","NEXT PHASE"],capm:"Milestones are common schedule concepts. Questions may test whether you recognize them as important events rather than normal work activities."},
 stakeholder:{title:"Stakeholder",simple:"A person or group that cares about, affects, or is affected by the project.",analogy:"If you're planning a wedding, the couple, venue, caterer, guests and planner can all care about or affect the outcome. Those are stakeholders.",example:"For TikTok Go, stakeholders include IT, Marketing, TikTok, Operations, restaurant managers, staff and leadership. For Mikan, vendors, managers, IT, Operations and ownership can all be stakeholders.",confused:"Stakeholder = who is involved. Workstream = what work is happening. Example: Marketing team is a stakeholder group; Marketing launch work can be a workstream.",industry:"A stakeholder is an individual, group or organization that may affect, be affected by or perceive itself to be affected by a project decision, activity or outcome.",visual:["IT · MARKETING · TIKTOK · OPS","↘   ↓   ↓   ↙","PROJECT","↓","MANAGERS · STAFF · LEADERSHIP"],capm:"Stakeholder identification, communication and engagement are core PM ideas and can appear frequently in CAPM-style scenarios."},
 risk:{title:"Risk",simple:"A problem that might happen, but has not happened yet.",analogy:"Dark clouds before a picnic are a risk because it might rain. Once it starts raining, it is no longer just a risk. It is now an actual problem.",example:"TikTok Go: a location's tablet might be too old to install the merchant app. Until you test it, that is a risk. If it actually cannot install the app, it becomes an issue.",confused:"Risk = might happen. Issue = is happening or already happened.",industry:"A risk is an uncertain event or condition that, if it occurs, has a positive or negative effect on one or more project objectives.",visual:["MIGHT HAPPEN","= RISK","↓ if it happens","IS HAPPENING","= ISSUE"],capm:"CAPM questions often test the difference between risks and issues and what a project manager should do before versus after an event occurs."},
 scope:{title:"Scope",simple:"What the project includes and what it does not include.",analogy:"If you hire someone to repaint your kitchen, the kitchen may be in scope. Repainting your bedroom is not automatically included just because it is in the same house.",example:"TikTok Go scope can include tablet readiness, merchant app access, menu sets, POS redemption, training and launch coordination. Rebuilding the entire POS system would not automatically be in scope.",confused:"Scope = boundaries of the work. Deliverable = a result produced within those boundaries.",industry:"Project scope defines the work required to deliver the project's agreed product, service or result.",visual:["PROJECT BOUNDARY","[ INCLUDED WORK ]","OUTSIDE THE BOX = NOT IN SCOPE"],capm:"Scope questions often test what to do when someone asks for work that was not part of the agreed project."},
 raci:{title:"RACI",simple:"A chart that shows who does the work and who needs to be involved.",analogy:"Think of assigning chores at home. One person does the task, one person ultimately owns the result, some people give input and others just need to know what happened.",example:"For TikTok Go, IT might be Responsible for POS setup, Marketing may be Accountable for launch coordination, Operations may be Consulted on training and managers may be Informed of go-live timing.",confused:"RACI is about responsibility, not schedule. It answers 'who is involved in this work?' rather than 'when does this happen?'.",industry:"RACI stands for Responsible, Accountable, Consulted and Informed. It is a responsibility assignment matrix used to clarify roles.",visual:["R = DOES THE WORK","A = OWNS THE RESULT","C = GIVES INPUT","I = KEPT UPDATED"],capm:"RACI is useful for questions about role clarity, ownership and stakeholder communication."},
 jira:{title:"Jira",simple:"A tool for keeping project work organized.",analogy:"Think of it like a digital wall of sticky notes where each piece of work can have a name, owner, status and due date.",example:"We are using Jira to organize the TikTok Go rollout so tasks like tablet readiness, menu programming, manager training and launch confirmation can be tracked instead of living in emails or memory.",confused:"Jira is the tool. Project-management methods are the way you decide how to organize and manage the work. Using Jira does not automatically mean a project is well managed.",industry:"Jira is Atlassian work-management software commonly used to track tasks, issues, workflows, backlogs and project status.",visual:["PROJECT","↓","JIRA WORK ITEMS","↓","OWNER · STATUS · DUE DATE","↓","TRACK PROGRESS"]},
 epic:{title:"Epic",simple:"A big chunk of work that is too large to be just one task.",analogy:"If 'Plan a vacation' is too big for one checkbox, you might split it into flights, hotel, activities and packing. The big vacation-planning item is like an Epic; the smaller pieces are tasks.",example:"For TikTok Go, 'Location & Device Readiness' can be an Epic. Under it, you could have tasks for checking tablet compatibility, confirming app-store access and installing the merchant app.",confused:"Epic = large group of related work. Task = smaller piece of work inside that larger area. Jira setups can vary, so the exact hierarchy depends on how the project is configured.",industry:"In Jira, an Epic is commonly used to group a large body of related work that can be broken into smaller work items.",visual:["EPIC","LOCATION & DEVICE READINESS","↓","TASK: CHECK TABLET","TASK: APP STORE ACCESS","TASK: INSTALL APP"]}
};

function save(){localStorage.setItem(stateKey,JSON.stringify(state));}
function ensureTask(id){if(!state.tasks[id])state.tasks[id]={done:false,checks:{},steps:{},notes:""};if(!state.tasks[id].steps)state.tasks[id].steps={};return state.tasks[id];}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function termButton(term,label){return `<button type="button" class="term" data-term="${term}">${label||glossary[term].title}</button>`;}
function linkifyTerms(text){let s=escapeHtml(text);[[/\bCAPM\b/g,"capm"],[/\bworkstreams?\b/gi,"workstream"],[/\bdeliverables?\b/gi,"deliverable"],[/\bdependencies\b|\bdependency\b/gi,"dependency"],[/\bmilestones?\b/gi,"milestone"],[/\bstakeholders?\b/gi,"stakeholder"],[/\brisks?\b/gi,"risk"],[/\bscope\b/gi,"scope"],[/\bRACI\b/g,"raci"],[/\bJira\b/g,"jira"],[/\bEpics?\b/g,"epic"]].forEach(([re,key])=>{s=s.replace(re,m=>termButton(key,m));});return s;}
function formatDate(t){if(!t.date)return t.day;return new Date(`${t.date}T12:00:00`).toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"});}

function openTerm(key){
 const g=glossary[key];if(!g)return;
 let m=document.getElementById("termModal");
 if(!m){
  m=document.createElement("div");m.id="termModal";m.className="term-modal hidden";
  m.innerHTML='<div class="term-backdrop"></div><section class="term-dialog" role="dialog" aria-modal="true"><button class="term-close" type="button" aria-label="Close">×</button><div class="kicker">Learn this concept</div><h2></h2><section class="learn-block simple-block"><div class="learn-label">Super simple</div><p class="term-simple"></p></section><section class="learn-block"><div class="learn-label">Think of it like this</div><p class="term-analogy"></p></section><section class="learn-block"><div class="learn-label">Your real project example</div><p class="term-example"></p></section><div class="term-visual"></div><section class="learn-block confused-block"><div class="learn-label">Easy to confuse with</div><p class="term-confused"></p></section><details class="learn-more"><summary>More PM / industry detail</summary><div class="learn-more-body"><p class="term-industry"></p><div class="term-capm"></div></div></details></section>';
  document.body.appendChild(m);
  m.querySelector(".term-close").onclick=()=>m.classList.add("hidden");
  m.querySelector(".term-backdrop").onclick=()=>m.classList.add("hidden");
 }
 m.querySelector("h2").textContent=g.title;
 m.querySelector(".term-simple").textContent=g.simple;
 m.querySelector(".term-analogy").textContent=g.analogy||"";
 m.querySelector(".term-example").textContent=g.example||"";
 m.querySelector(".term-confused").textContent=g.confused||"Nothing important to compare yet.";
 m.querySelector(".term-industry").innerHTML=`<strong>Industry meaning:</strong> ${escapeHtml(g.industry||g.simple)}`;
 const capm=m.querySelector(".term-capm");
 capm.innerHTML=g.capm?`<strong>CAPM connection:</strong> ${escapeHtml(g.capm)}`:"";
 capm.classList.toggle("hidden",!g.capm);
 m.querySelector(".term-visual").innerHTML=g.visual.map(x=>`<div>${escapeHtml(x)}</div>`).join("");
 m.classList.remove("hidden");
}
document.addEventListener("click",e=>{const b=e.target.closest(".term");if(b){e.preventDefault();openTerm(b.dataset.term);}});
document.addEventListener("keydown",e=>{if(e.key==="Escape")document.getElementById("termModal")?.classList.add("hidden");});

function renderStats(){const cats=["PM / CAPM","Technical","Portfolio","Job Search"],box=document.getElementById("stats");box.innerHTML="";cats.forEach(cat=>{const ts=data.tasks.filter(t=>t.category===cat),done=ts.filter(t=>ensureTask(t.id).done).length,pct=ts.length?Math.round(done/ts.length*100):0;box.insertAdjacentHTML("beforeend",`<div class="stat"><div class="stat-label">${linkifyTerms(cat)}</div><div class="bar"><div class="fill" style="width:${pct}%"></div></div><div class="stat-pct">${pct}%</div></div>`);});}

function normalizeItem(item){return typeof item==="string"?{title:item,description:"",steps:[]}:item;}
function makeTask(task){const tpl=document.getElementById("taskTemplate"),el=tpl.content.firstElementChild.cloneNode(true),s=ensureTask(task.id);el.dataset.id=task.id;el.classList.toggle("done",s.done);el.querySelector(".task-title").innerHTML=linkifyTerms(task.title);el.querySelector(".minutes").textContent=`${task.minutes} min`;el.querySelector(".meta").innerHTML=`${formatDate(task)} · ${linkifyTerms(task.category)}`;el.querySelector(".details").innerHTML=linkifyTerms(task.details);const main=el.querySelector(".task-check");main.checked=s.done;main.onchange=()=>{s.done=main.checked;save();renderAll();};const list=el.querySelector(".checklist");
 task.checklist.forEach((raw,i)=>{const item=normalizeItem(raw),wrap=document.createElement("div");wrap.className="check-group";const head=document.createElement("div");head.className="check-group-head";const cb=document.createElement("input");cb.type="checkbox";cb.className="subcheck";cb.checked=!!s.checks[i];cb.onchange=()=>{s.checks[i]=cb.checked;save();};const content=document.createElement("div");content.className="check-content";content.innerHTML=`<div class="check-title">${linkifyTerms(item.title)}</div>${item.description?`<div class="check-description">${linkifyTerms(item.description)}</div>`:""}`;head.append(cb,content);wrap.appendChild(head);
  if(item.steps?.length){const details=document.createElement("details");details.className="step-panel";details.innerHTML=`<summary>Show exactly what to do <span class="step-count">${item.steps.length} steps</span></summary>`;const steps=document.createElement("div");steps.className="steps";item.steps.forEach((step,j)=>{const row=document.createElement("label");row.className="step-row";const sc=document.createElement("input");sc.type="checkbox";const k=`${i}:${j}`;sc.checked=!!s.steps[k];sc.onchange=()=>{s.steps[k]=sc.checked;save();};const tx=document.createElement("span");tx.innerHTML=linkifyTerms(step);row.append(sc,tx);steps.appendChild(row);});details.appendChild(steps);wrap.appendChild(details);}
  list.appendChild(wrap);
 });
 const notes=el.querySelector(".notes");notes.value=s.notes||"";notes.oninput=()=>{s.notes=notes.value;save();};return el;}

function renderDaily(){const box=document.getElementById("daily"),today=new Date().toLocaleDateString("en-CA"),sorted=[...data.tasks].sort((a,b)=>a.date.localeCompare(b.date));let task=sorted.find(t=>t.date===today&&!ensureTask(t.id).done)||sorted.find(t=>t.date===today)||sorted.find(t=>!ensureTask(t.id).done&&t.date<today)||sorted.find(t=>!ensureTask(t.id).done);box.innerHTML="";if(!task){box.innerHTML='<div class="empty">Everything currently listed is complete.</div>';return;}box.innerHTML=`<div class="today-hero"><div class="kicker">Current daily task</div><h2>${escapeHtml(task.title)}</h2><p>${formatDate(task)} · ${task.minutes} minutes</p><p class="sub">Open each checklist section below. The heading tells you the outcome, the description tells you why it matters, and <strong>Show exactly what to do</strong> gives you the concrete steps.</p></div>`;box.appendChild(makeTask(task));}
function renderWeekly(){const box=document.getElementById("weekly");box.innerHTML="";const groups={};[...data.tasks].sort((a,b)=>a.date.localeCompare(b.date)).forEach(t=>{const k=`${t.month} · ${t.week}`;(groups[k]??=[]).push(t);});Object.entries(groups).forEach(([k,ts])=>{const sec=document.createElement("section");sec.className="day-block";sec.innerHTML=`<div class="day-label">${escapeHtml(k)}</div><div class="grid"></div>`;ts.forEach(t=>sec.querySelector(".grid").appendChild(makeTask(t)));box.appendChild(sec);});}
function renderMonthly(){const box=document.getElementById("monthly");box.innerHTML='<div class="grid two"></div>';const grid=box.firstElementChild;data.months.forEach(m=>{const c=document.createElement("article");c.className="card month-card";c.innerHTML=`<div class="kicker">${escapeHtml(m.month)}</div><h3>${linkifyTerms(m.focus)}</h3><ul>${m.items.map(x=>`<li>${linkifyTerms(x)}</li>`).join("")}</ul>`;grid.appendChild(c);});}
function renderAll(){renderStats();renderDaily();renderWeekly();renderMonthly();}

document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));document.getElementById(b.dataset.view).classList.remove("hidden");});
document.getElementById("resetBtn").onclick=()=>{if(confirm("Reset all saved progress and notes on this browser?")){state={tasks:{}};save();renderAll();}};
fetch("roadmap.json").then(r=>r.json()).then(d=>{data=d;renderAll();}).catch(()=>{document.getElementById("daily").innerHTML='<div class="empty">Could not load roadmap.json.</div>';});